### PR TITLE
Get ScriptableObjects from all loaded assemblies

### PR DESCRIPTION
**Pull request by petereichinger**
Instead of only loading the main assembly. Get all loaded assemblies and add them to the window.

### CODE REVIEW

**Comment by revolt3r** [comment]
You would want to avoid getting all assemblies, especially in a big project, it would create a lot of unnecessary overhead.

**Review by revolt3r — APPROVED** [review]

**Comment by petereichinger** [comment]
Hmm I could look into making a preference pane that allows adding some assemblies to an ignore list.

**Comment by revolt3r** [comment]
There are 116 Assemblies in a new Unity Project, most of them are irrelevant to 99% of people.
image

**Comment by revolt3r** [comment]
Added assembly selection

**Pull request merged**
